AuthservID mail.lab.test
TrustedAuthservIDs mail.lab.test
IgnoreAuthenticatedClients false
RejectFailures false
Socket inet:8893@0.0.0.0
SPFSelfValidate true
PublicSuffixList /usr/share/publicsuffix/public_suffix_list.dat
PidFile /run/opendmarc/opendmarc.pid
