protocols = imap lmtp
listen = *
ssl = no
disable_plaintext_auth = no
auth_mechanisms = plain login
auth_username_format = %Ln
mail_privileged_group = vmail
mail_location = maildir:/var/mail/%n/Maildir
first_valid_uid = 5000

passdb {
  driver = static
  args = password=lab-bob
}
userdb {
  driver = static
  args = uid=vmail gid=vmail home=/var/mail/%n
}

service lmtp {
  inet_listener lmtp {
    address = 0.0.0.0
    port = 24
  }
}

service imap-login {
  inet_listener imap {
    address = 0.0.0.0
    port = 143
  }
}
