server:
    directory: "/etc/unbound"
    username: "unbound"
    chroot: ""
    interface: 127.0.0.1
    port: 53
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    access-control: 127.0.0.0/8 allow
    verbosity: 1
    use-syslog: no
    logfile: "/var/log/unbound.log"
    do-daemonize: yes
    val-permissive-mode: yes
    domain-insecure: "lab.test."
forward-zone:
    name: "."
    forward-addr: 10.88.0.53
